import type { AIProvenance } from "@/src/lib/ai/types";

export function AIProvenanceCard({
  provenance,
  title = "Generated by Gemini · Review before confirming",
}: {
  provenance: AIProvenance;
  title?: string;
}) {
  return (
    <div className="rounded-2xl border border-violet-200 bg-violet-50/70 p-4">
      <p className="text-xs font-bold uppercase tracking-[0.12em] text-violet-700">
        {title}
      </p>
      <dl className="mt-3 grid gap-2 text-xs text-violet-950/75 sm:grid-cols-2">
        <div>
          <dt className="font-bold text-violet-950">Provider</dt>
          <dd>{provenance.provider}</dd>
        </div>
        <div>
          <dt className="font-bold text-violet-950">Model</dt>
          <dd>{provenance.model}</dd>
        </div>
        <div>
          <dt className="font-bold text-violet-950">Mode</dt>
          <dd className="capitalize">{provenance.mode}</dd>
        </div>
        <div>
          <dt className="font-bold text-violet-950">Generated</dt>
          <dd>{new Date(provenance.generatedAt).toLocaleString()}</dd>
        </div>
      </dl>
      {provenance.humanConfirmationRequired && (
        <p className="mt-3 text-xs font-semibold text-violet-900">
          Human confirmation required
        </p>
      )}
    </div>
  );
}
