import {
  cleanup,
  fireEvent,
  render,
  screen,
  waitFor,
} from "@testing-library/react";
import { afterEach, beforeEach, expect, it, vi } from "vitest";

import { BudgetBuilder } from "@/src/components/budget-builder";

const treasuryId = "11111111-1111-4111-8111-111111111111";
const state = vi.hoisted(() => ({ fetch: vi.fn(), push: vi.fn() }));

vi.mock("next/navigation", () => ({
  useRouter: () => ({ push: state.push }),
  useSearchParams: () => new URLSearchParams(`treasury=${treasuryId}`),
}));

vi.mock("@/src/config/public-env", () => ({
  publicConfig: { claimDataMode: "live" },
}));

beforeEach(() => {
  state.fetch.mockReset();
  state.push.mockReset();
  state.fetch.mockImplementation(
    async (input: RequestInfo | URL, init?: RequestInit) => {
      const url = String(input);
      if (url === "/api/treasuries") {
        return {
          ok: true,
          json: async () => ({
            treasuries: [
              {
                id: treasuryId,
                externalReference: "gemini-demo-2026",
                name: "Gemini Demo Treasury",
                totalBudgetMinor: 1_000,
                suiTreasuryObjectId: null,
                linkedToSui: false,
                role: "owner",
                categories: [],
              },
            ],
          }),
        } as Response;
      }
      if (url === "/api/ai/budget-draft") {
        expect(init?.method).toBe("POST");
        return {
          ok: true,
          json: async () => ({
            draft: {
              currency: "USDC",
              categories: [
                { name: "Food", amountMinor: 400 },
                { name: "Marketing", amountMinor: 300 },
                { name: "Transport", amountMinor: 200 },
                { name: "Miscellaneous", amountMinor: 100 },
              ],
              notes: [],
            },
            provenance: {
              provider: "Google Gemini",
              model: "gemini-2.5-flash",
              mode: "live",
              task: "budget_draft",
              generatedAt: "2026-09-05T07:30:00.000Z",
              humanConfirmationRequired: true,
            },
          }),
        } as Response;
      }
      if (url === `/api/treasuries/${treasuryId}/budget`) {
        return {
          ok: true,
          json: async () => ({ categories: [] }),
        } as Response;
      }
      throw new Error(`Unexpected fetch: ${url}`);
    },
  );
  vi.stubGlobal("fetch", state.fetch);
});

afterEach(() => {
  cleanup();
  vi.unstubAllGlobals();
});

it("uses Gemini only to populate an editable draft and persists only after human confirmation", async () => {
  render(<BudgetBuilder />);

  expect(await screen.findByText("Gemini Demo Treasury")).toBeInTheDocument();

  fireEvent.change(screen.getByLabelText(/describe your budget/i), {
    target: {
      value: "4 food, 3 marketing, 2 transport, 1 miscellaneous",
    },
  });
  fireEvent.click(screen.getByRole("button", { name: /generate with gemini/i }));

  expect(await screen.findByDisplayValue("Food")).toBeInTheDocument();
  expect(screen.getByDisplayValue("4.00")).toBeInTheDocument();
  expect(screen.getByText(/generated by gemini/i)).toBeInTheDocument();
  expect(screen.getByText(/review before confirming/i)).toBeInTheDocument();

  const budgetWritesBeforeConfirm = state.fetch.mock.calls.filter(
    ([url, options]) =>
      String(url).includes(`/api/treasuries/${treasuryId}/budget`) &&
      (options as RequestInit | undefined)?.method === "PUT",
  );
  expect(budgetWritesBeforeConfirm).toHaveLength(0);

  const confirmButton = screen.getByRole("button", {
    name: /^confirm budget$/i,
  });
  await waitFor(() => expect(confirmButton).toBeEnabled());
  fireEvent.click(confirmButton);

  await waitFor(() => {
    expect(state.fetch).toHaveBeenCalledWith(
      `/api/treasuries/${treasuryId}/budget`,
      expect.objectContaining({
        method: "PUT",
        body: JSON.stringify({
          categories: [
            { name: "Food", allocationMinor: 400 },
            { name: "Marketing", allocationMinor: 300 },
            { name: "Transport", allocationMinor: 200 },
            { name: "Miscellaneous", allocationMinor: 100 },
          ],
        }),
      }),
    );
  });
});
